import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      //myadmin
      name: 'Raushan',
      email: 'raushanranjan145@gmail.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: 
    [
        {
            name: 'Power Block Dumbbells 5-kg',
            slug: 'power-block-dumbbells',
            category:'Gym',
            image:'/images/p1.jpg',
            price: 350,
            countInStock:10,
            brand: 'Power Block',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality dumbbells',
        },
        {
            name: ' Nike Badminton racket',
            slug: 'nike-badminton-racket',
            category:'Sports',
            image:'/images/p2.jpg',
            price: 1350,
            countInStock:56,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            name: 'SG Cricket Bat',
            slug: 'sg-cricket-bat',
            category:'Sports',
            image:'/images/p3.jpg',
            price: 1500,
            countInStock:10,
            brand: 'SG',
            rating: 4.3,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            name: 'DBMS TEXTBOOK for 5th sem',
            slug: 'dbms-textbook',
            category:'Books',
            image:'/images/p4.jpg',
            price: 356,
            countInStock:17,
            brand: 'Cengage',
            rating: 4.9,
            numReviews: 40,
            description: 'written in simple language',
        },
        {
            name: 'Skipping rope',
            slug: 'skipping-rope',
            category:'Sports',
            image:'/images/p5.jpg',
            price: 600,
            countInStock:10,
            brand: 'Addidas',
            rating: 4.9,
            numReviews: 70,
            description: 'good product',
        },
        {
            name: 'CN TEXTBOOK for 5th sem',
            slug: 'cn-textbook',
            category:'Books',
            image:'/images/p6.jpg',
            price: 457,
            countInStock:17,
            brand: 'MK PUBLICATIONS',
            rating: 4.9,
            numReviews: 40,
            description: 'written in simple language',
        },
        {
            name: 'MEDICINE BALL',
            slug: 'medine-ball',
            category:'Health',
            image:'/images/p7.jpg',
            price: 500,
            countInStock:17,
            brand: 'Nivia',
            rating: 4.9,
            numReviews: 60,
            description: 'good product',
        },
        {
            name: 'YOGA MAT',
            slug: 'yoga-mat',
            category:'Health',
            image:'/images/p8.jpg',
            price: 300,
            countInStock:17,
            brand: 'Nike',
            rating: 4.9,
            numReviews: 40,
            description: 'good product',
        },
        {
            name: 'Boat FitBit Band',
            slug: 'boat-fit-bit-band',
            category:'Health',
            image:'/images/p9.jpg',
            price: 3000,
            countInStock:897,
            brand: 'Boat',
            rating: 4.9,
            numReviews: 840,
            description: 'good product',
        },
        {
            name: 'Magnetic ChessBoard',
            slug: 'magnetic-chessboard',
            category:'Sports',
            image:'/images/p10.jpg',
            price: 1400,
            countInStock:10,
            brand: 'Nike',
            rating: 4.7,
            numReviews: 400,
            description: 'good product',
        },
       
    ],
};
export default data;